# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Kohei Watanabe
title: Fullstack Developer & (Past) Machine Learning Researcher
email: littlewat.dev@gmail.com
# website: https://github.com/LittleWat

# Social links
github_username: LittleWat
stackoverflow_username: "5986291"
linkedin_username: kohei-watanabe-73990010b
twitter_username: humilittle
additional_links:
  - title: hatena
    url: https://littlewat.hatenadiary.jp/
    icon: fa-blogger-b
  - title: qiita
    url: https://qiita.com/LittleWat
    icon: fa-quora
  - title: google-scholar
    url: https://scholar.google.co.jp/citations?user=lejuP2AAAAAJ
    icon: fa-google

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name's Kohei and I'm a fullstack developer (mobile apps, spring boot, nodejs, python, etc...).
  As well as developing mobile apps, I also have experience research in machine learning filed. 
  I am passionate to learn new things and like to share the knowledge.
  `Refactoring`, `TDD`, `DDD` interests me a lot.

  I am most skilled in: <mark>iOS App Development</mark>, <mark>Data Analysis (includes Deep Learning)</mark>, <mark>AWS</mark> and <mark>Eating Ramen🍜</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs

  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Shogi (3-dan)
   - Jogging (attended `Oume` Marathon)
   - Netflix

# Footers
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

theme: jekyll-theme-cayman
